name: Scheduled Netlify Build
on:
  schedule:
    # every half hour, from 6am to midnight
    - cron: "0,30 6-23 * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_WEBHOOK }}
