name: Scheduled Netlify Build
on:
  schedule:
    - cron: "15 8,10,12,14,16,18 * * *"
jobs:
  build:
    name: Call Netlify build hook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_WEBHOOK }}
