name: PR Tests
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - main

jobs:
  test:
    name: Run a test build
    runs-on: ubuntu-20.04
    permissions: read-all
    outputs:
      job-status: ${{job.status}}
    steps:
      - name: Checkout Code
        id: git-checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}

      - name: Run A Build
        run: npm run build
